if: (type = push AND branch IN (master, develop)) OR (type = pull_request AND NOT branch =~ /no-ci/)

language: node_js

node_js:
  - "14"
  - "12"
  - "10"

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
