if: (type = push AND branch = master) OR (type = pull_request AND NOT branch =~ /no-ci/)

language: node_js

node_js:
  - "16"
  - "14"
  - "12"

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
