language: node_js

node_js:
  - "14"
  - "12"
  - "10"

branches:
  only:
    - master

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
